spring.application.name=file-fetcher

server.port=8082


# MongoDB Configuration

# Import OS-specific configurations and scheduled tasks
spring.config.import=file:./config/transfer-pairs.yml

# Spring Boot specific logging
logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.context=DEBUG
logging.level.org.springframework.core=DEBUG
logging.level.org.springframework.beans=DEBUG

# Your application logging
logging.level.dplg.apps.acars=DEBUG

# To see configuration properties loading
logging.level.org.springframework.boot.context.properties=DEBUG