parserfile-collector:
  check-interval-ms: 60000  # Common 1-minute interval for all pairs
  max-days: 5   # Maximum number of files to process per batch per pair
  collectors:
    - source: /mnt/cfd_share
      target: /opt/acars/collector/data/cfd
      archive: /mnt/cfd_share/archive
      file-pattern: "*.txt"
    - source: /mnt/oooi_share
      target: /opt/acars/collector/data/oooi
      archive: /mnt/oooi_share/archive
      file-pattern: "*.txt"